### ISSUE TITLE
Can't cancel out of save/restore/transcript

### ISSUE THREAD

**Issue by adibianca** [curiousdannii/emglken#11]
Problem appears in Lectrote 1.3.2, Windows x64 version.
When running a Glulx game with Git or Glulxe interpreters, typing SAVE, RESTORE, or TRANSCRIPT, and then canceling, causes the game to crash with “fileref_create_by_prompt: unable to create fileref”.

Zarf suggested this was an issue with emglken.

**Comment by curiousdannii** [comment]
Pretty sure this has already been fixed. I'll check and then send a PR with the updated emglken code to Lectrote.
