### ISSUE TITLE
Test TADS 2/3

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/emglken#17]
I'm not sure if there are unit test storyfiles, or else what would be some good example games that we can distribute here would be? Any suggestions?

**Comment by cibersheep** [comment]
I use:
Nothing but Mazes for TADS 3
https://ifdb.tads.org/viewgame?id=ovbxika0f1e03g6i

And Firebird for TADS 2
https://ifdb.tads.org/viewgame?id=d9h1r3d920ap8ajf

**Comment by cibersheep** [comment]
Oh, I forgot... Nothing but Mazes is not supported by tadsr. Sorry about that

**Comment by curiousdannii** [comment]
I'll probably use Return to Ditch Day as it explicitly allows redistribution.
