### ISSUE TITLE
Suggestion / Question: Have you thought about switching to WASI for file system and stdio etc?

### ISSUE THREAD

**Issue by danielbodart** [curiousdannii/emglken#28]
https://wasi.dev/

This would could allow the wasm binaries to run in a lot more places, potentially [Cloudflare Workers](https://developers.cloudflare.com/workers/runtime-apis/webassembly/) or [Fermyon Spin](https://www.fermyon.com/spin)

I know you have been using Rust for the remglk-rs version, but you could probably just use Zig and directly compile the original remglk and all interpreters and target wasi binary with minimal code change to any of them.

I am no expert on Zig or wasi mind you

**Comment by curiousdannii** [comment]
We need Asyncify, which I don't think works in WASI. The web is the main use for this, with console second, so even if WASI would be possible I haven't investigated it. I'm not in theory opposed to a pull request moving more in a WASI direction, but it's not something I'm intending to look into.
